language: java
sudo: false
jdk:
- oraclejdk9
install:
- |
  if [[ -n "${TRAVIS_TAG}" ]]; then
    curl -o antkit.tar.gz -L https://github.com/cryptomator/cryptomator/releases/download/${TRAVIS_TAG}/antkit.tar.gz
  else
    curl -o antkit.tar.gz -L https://github.com/cryptomator/cryptomator/releases/download/continuous/antkit.tar.gz
  fi
- tar -xzf antkit.tar.gz
script:
- ./build.sh
